# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-21 14:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jedi', '0002_auto_20170519_2149'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='jedi',
            managers=[
            ],
        ),
    ]
